--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Aericio/PCEBookShop
build-by-default: true
branches:
- master
projects:
  PCEBookShop:
    path: ""
    libs:
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.1
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.1
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
    lint:
      phpstan: false
...
