name: PCEBookShop
main: Aericio\PCEBookShop\PCEBookShop
version: 2.0.0
api: 4.0.0
load: POSTWORLD
author: Aericio
depend: [PiggyCustomEnchants]
soft-depend: [EconomyAPI, MultiEconomy, BedrockEconomy]
website: "https://github.com/Aericio/PCEBookShop/"
permissions:
  pcebookshop.command.bookshop:
    default: true
